default:
  app:
    name: Driver API
    version: 1.0.0

  driver:
    id: U34F2JRRS

  broker:
    kafka:
      clientId: driverApi
      brokers:
        - velomobile-01.srvs.cloudkafka.com:9094
      consumerOptions:
        groupId: 'replace-me'
      topics:
        - ride__requested
        - ride__assigned
      topicSeparator: '__'
      topicPrefix:

development:

test:

staging:

production:
  broker:
    kafka:
      ssl:
        rejectUnauthorized: true
      sasl:
        mechanism: 'plain'
        username:
        password:
