default:
  app:
    name: User API
    version: 1.0.0

  ws:
    topics:
      - ride__requested
      - ride__assigned
    topicSeparator: '__'

  broker:
    kafka:
      clientId: userApi
      brokers:
        - velomobile-01.srvs.cloudkafka.com:9094
      consumerOptions:
        groupId: 'replace-me'
      topics:
        - ride__assigned
      topicSeparator: '__'
      topicPrefix:

development:

test:

staging:

production:
  broker:
    kafka:
      ssl:
        rejectUnauthorized: true
      sasl:
        mechanism: 'plain'
        username:
        password:
