version: '3'

services:
  kafka:
    image: spotify/kafka
    ports:
      - 9092:9092
    container_name: kafka
    environment:
      - "ADVERTISED_HOST=192.168.1.34"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"