default:
  app:
    name: Control Panel API
    version: 1.0.0

  broker:
    kafka:
      clientId: controlPanelApi
      brokers:
        - velomobile-01.srvs.cloudkafka.com:9094
      consumerOptions:
        groupId: 'replace-me'
      topics:
        - ride__requested
        - ride__accepted
      topicSeparator: '__'
      topicPrefix:

development:

test:

staging:

production:
  broker:
    kafka:
      ssl:
        rejectUnauthorized: true
      sasl:
        mechanism: 'plain'
        username:
        password:
