default:
  app:
    name: Ride App Control Panel API
    version: 1.0.0

  broker:
    kafka:
      clientId: rideAppControlPanelApi
      brokers:
        - velomobile-01.srvs.cloudkafka.com:9094
      consumerOptions:
        groupId: rideAppControlPanelApi
      topics:
        - driver-registered
        - ride-requested
        - ride-accepted
      topicSeparator: '__'
      topicPrefix:

development:

test:

staging:

production:
  broker:
    kafka:
      ssl:
        rejectUnauthorized: true
      sasl:
        mechanism: 'plain'
        username:
        password:
